### ISSUE TITLE
SBratio not a main parameter

### ISSUE THREAD

**Issue by dionysisskouras** [MadAnalysis/madanalysis5#103]
### Question

Hello I am using MA5 release 1.9.60 and I have datasets named SM and SUSY. When I give the command
set main.SBratio = 'SUSY/sqrt(SUSY+SM)' I get an error
'main' has no parameter called 'SBratio' but I've seen this parameter in manuals (from2012)
Any ideas?
Thank you
Dionysis

**Comment by jackaraz** [comment]
Hi @dionysisskouras 2012 is too old for v1.9.60 if you check the normal mode reference card in your local ma5 doc folder you will see that this command has been replaced by `main.fom.formula`

**Comment by dionysisskouras** [comment]
Thank you i just did that and I got the following error
set main.fom.formula = "S/sqrt(B)"
Traceback (most recent call last):
  File "./bin/ma5", line 77, in <module>
    madanalysis.core.launcher.LaunchMA5(version, date, ma5dir)
  File "/home/dionysis/ma5/madanalysis5-1.9.60/madanalysis/core/launcher.py", line 430, in LaunchMA5
    repeat = MainSession(mode,arglist,ma5dir,version,date)
  File "/home/dionysis/ma5/madanalysis5-1.9.60/madanalysis/core/launcher.py", line 334, in MainSession
    interpreter.cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/home/dionysis/ma5/madanalysis5-1.9.60/madanalysis/interpreter/interpreter.py", line 133, in do_set
    self.cmd_set.do(self.split_arg(line),line)
  File "/home/dionysis/ma5/madanalysis5-1.9.60/madanalysis/interpreter/cmd_set.py", line 292, in do
    self.do_main(args2)
  File "/home/dionysis/ma5/madanalysis5-1.9.60/madanalysis/interpreter/cmd_set.py", line 140, in do_main
    self.main.fom.user_SetParameter(objs[2],args[2])
  File "/home/dionysis/ma5/madanalysis5-1.9.60/madanalysis/configuration/fom_configuration.py", line 68, in user_SetParameter
    self.logger.error("The only possible values for 'formula' are : "+' '.str(FomConfiguration.userVariables["formula"]+'.'))
AttributeError: 'str' object has no attribute 'str'

**Comment by jackaraz** [comment]
Have you read the reference card?


--
Jack Y. Araz

**Comment by jackaraz** [comment]
Closing this issue since there has been no activity, please feel free to reopen it if the problem persists.
