### ISSUE TITLE
Issue with matplotlib 

### ISSUE THREAD

**Issue by juhidutta** [MadAnalysis/madanalysis5#144]
### Question

Dear Experts,

I am currently working with the latest version of madanalysis5. While making a sample run in the normal mode, I receive the following error message and no plots are generated.

python all.py 
BEGIN-STAMP
- Producing histo selection_0...
/raid05/users/jdutta/madanalysis5-main/bbMET/Output/Histos/MadAnalysis5job_0/selection_0.py:40: MatplotlibDeprecationWarning: 
The 'normed' kwarg was deprecated in Matplotlib 2.1 and will be removed in 3.1. Use 'density' instead.
  bottom=None, cumulative=False, normed=False, align="mid", orientation="vertical")
/raid05/users/jdutta/madanalysis5-main/bbMET/Output/Histos/MadAnalysis5job_0/selection_0.py:45: MatplotlibDeprecationWarning: 
The 'normed' kwarg was deprecated in Matplotlib 2.1 and will be removed in 3.1. Use 'density' instead.
  bottom=None, cumulative=False, normed=False, align="mid", orientation="vertical")
/raid05/users/jdutta/madanalysis5-main/bbMET/Output/Histos/MadAnalysis5job_0/selection_0.py:50: MatplotlibDeprecationWarning: 
The 'normed' kwarg was deprecated in Matplotlib 2.1 and will be removed in 3.1. Use 'density' instead.
  bottom=None, cumulative=False, normed=False, align="mid", orientation="vertical")
/raid05/users/jdutta/madanalysis5-main/bbMET/Output/Histos/MadAnalysis5job_0/selection_0.py:55: MatplotlibDeprecationWarning: 
The 'normed' kwarg was deprecated in Matplotlib 2.1 and will be removed in 3.1. Use 'density' instead.
  bottom=None, cumulative=False, normed=False, align="mid", orientation="vertical")
Traceback (most recent call last):
  File "all.py", line 25, in <module>
    selection_0.selection_0()
  File "/raid05/users/jdutta/madanalysis5-main/bbMET/Output/Histos/MadAnalysis5job_0/selection_0.py", line 77, in selection_0
    plt.gca().set_yscale("log",nonpositive="clip")
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_97apython3/x86_64-centos7-gcc8-opt/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 3702, in set_yscale
    ax.yaxis._set_scale(value, **kwargs)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_97apython3/x86_64-centos7-gcc8-opt/lib/python3.7/site-packages/matplotlib/axis.py", line 799, in _set_scale
    self._scale = mscale.scale_factory(value, self, **kwargs)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_97apython3/x86_64-centos7-gcc8-opt/lib/python3.7/site-packages/matplotlib/scale.py", line 743, in scale_factory
    return _scale_mapping[scale](axis, **kwargs)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_97apython3/x86_64-centos7-gcc8-opt/lib/python3.7/site-packages/matplotlib/scale.py", line 389, in __init__
    "{!r}".format(kwargs))
ValueError: provided too many kwargs, can only pass {'basex', 'subsx', nonposx'} or {'basey', 'subsy', nonposy'}.  You passed {'nonpositive': 'clip'}
[jdutta@ouhep05 MadAnalysis5job_0]$ 

I tried replacing the 'normed' to 'density' in the selection_0.py file but the error persists. The matplot-lib version in my system is 3.1.0. 

My system settings are as follows:

Operating System: centOS
Python version: Python 3.7.6
gcc version: 8.3.0
MadAnalysis 5 version: MA5: MA5 release : 1.10.4 [ 2022/07/18 ]
Delphes-Delphes-3.5.0
Matplotlib: 3.1.0

Could you please kindly let me know how may I resolve this issue?

With best regards,
Juhi

**Comment by jackaraz** [comment]
Hi @juhidutta, have you tried with Matplotlib 3.4? If you check 

https://github.com/MadAnalysis/madanalysis5/blob/ec5d8b158e33b4178fe04441487ca3265b76d432/requirements.txt#L1-L5

we require a matplotlib version of at least 3.4. Please let me know if the problem persists.

**Comment by jackaraz** [comment]
Closing the issue due to no recent activity.
