### ISSUE TITLE
Error when using import <dirname> command

### ISSUE THREAD

**Issue by robinhayes** [MadAnalysis/madanalysis5#146]
I've installed MadAnalysis5 v. 1.9.60 and am attempting to run MadAnalysis in Normal Mode on the set of samples that can be obtained by doing `install samples`. So I've done:

```
./bin/ma5 
install samples
import samples/ttbar*lhe* as ttbar
define l = l+ l-
plot PT(l[1]) 50 0 500
submit ttbarPlot
```

This mostly gives me the expected output, which I will attach at ttbarPlot.zip. However, I'm confused about two aspects of the [documentation](https://arxiv.org/pdf/1206.1599.pdf). p. 59 states that "As an output, a Root file [57] is generated so that the analysis can be accessed later, as, e.g., directly in the Root framework or in a new session of MadAnalysis 5. In this last case, the SampleAnalyzer (executed) job can be imported by means of the command `import`: `import <dirname>`"

I have not been able to see a ROOT file. Could you point me to where it can be found, or do I misunderstand the expected output?

I also have not been able to get the `import <dirname>` command to work. In a fresh MadAnalysis5 session, `import ttbarPlot` results in an error. I will paste the output below. I'm not sure if I misunderstand how this `import` command should be used, or if this is a bug resulting from the use of `input` as a variable name on L168-171 of `cmd_import.py`. Any help would be much appreciated.

```
[rhayes@dhcp-132-175 madanalysis5$ ./bin/ma5 
MA5: 
MA5: *************************************************************
MA5: *                                                           *
MA5: *        W E L C O M E  to  M A D A N A L Y S I S  5        *
MA5: *                         ______  ______                    *
MA5: *                 /'\_/`\/\  __ \/\  ___\                   *
MA5: *                /\      \ \ \_\ \ \ \__/                   *
MA5: *                \ \ \__\ \ \  __ \ \___``\                 *
MA5: *                 \ \ \_/\ \ \ \/\ \/\ \_\ \                *
MA5: *                  \ \_\\ \_\ \_\ \_\ \____/                *
MA5: *                   \/_/ \/_/\/_/\/_/\/___/                 *
MA5: *                                                           *
MA5: *   MA5 release : 1.9.60                       2021/12/13   *
MA5: *                                                           *
MA5: *         Comput. Phys. Commun. 184 (2013) 222-256          *
MA5: *             Eur. Phys. J. C74 (2014) 3103                 *
MA5: *                                                           *
MA5: *   The MadAnalysis Development Team - Please visit us at   *
MA5: *            https://launchpad.net/madanalysis5             *
MA5: *                                                           *
MA5: *              Type 'help' for in-line help.                *
MA5: *                                                           *
MA5: *************************************************************
MA5: Platform: Darwin 19.6.0 [MAC/OSX mode]
MA5: Reading user settings ...
MA5: Checking mandatory packages:
MA5:      - Python                   [OK]
MA5:      - GNU GCC g++              [OK]
MA5:      - GNU Make                 [OK]
MA5: Checking optional packages devoted to data processing:
MA5:      - Zlib                     [DISABLED]
MA5:      - FastJet                  [OK]
MA5:      - Root                     [OK]
MA5:      - Delphes                  [DISABLED]
MA5:      - Delphes-MA5tune          [DISABLED]
MA5: Checking the MadAnalysis 5 core library:
MA5:   => MadAnalysis libraries found.
MA5:   => MadAnalysis test program works.
MA5: Reading user settings ...
MA5: Checking optional packages devoted to reinterpretation:
MA5:      - SciPy                    [OK]
MA5:      - PAD                      [DISABLED]
MA5:      - PADForMA5tune            [DISABLED]
MA5:      - PADForSFS                [DISABLED]
MA5:      - pyhf                     [OK]
MA5: Checking optional packages devoted to histogramming:
MA5:      - Root                     [OK]
MA5:      - Matplotlib               [OK]
MA5:      - gnuplot                  [DISABLED]
MA5-WARNING: gnuplot disabled. Plots in gnuplot format file will not be produced.
MA5:      - pdflatex                 [OK]
MA5:      - latex                    [OK]
MA5: Package used for graphical rendering: Root
MA5: *************************************************************
MA5: Particle labels exported from madanalysis/input/particles_name_default.txt
MA5:   => 87 particles successfully exported.
MA5: Multiparticle labels exported from madanalysis/input/multiparticles_default.txt
MA5:   => Creation of the label 'invisible' (-> missing energy).
MA5:   => Creation of the label 'hadronic' (-> jet energy).
MA5:   => 8 multiparticles successfully exported.
ma5>import ttbarPlot
MA5: SampleAnalyzer job folder is detected
MA5: Restore MadAnalysis configuration used for this job ...
MA5-WARNING: You are going to reinitialize MadAnalysis 5. The current configuration will be lost.
MA5-WARNING: Are you sure to do that ? (Y/N)
Traceback (most recent call last):
  File "/Applications/madanalysis5/./bin/ma5", line 77, in <module>
    madanalysis.core.launcher.LaunchMA5(version, date, ma5dir)
  File "/Applications/madanalysis5/madanalysis/core/launcher.py", line 430, in LaunchMA5
    repeat = MainSession(mode,arglist,ma5dir,version,date)
  File "/Applications/madanalysis5/madanalysis/core/launcher.py", line 334, in MainSession
    interpreter.cmdloop()
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/cmd.py", line 217, in onecmd
    return func(arg)
  File "/Applications/madanalysis5/madanalysis/interpreter/interpreter.py", line 205, in do_import
    self.cmd_import.do(self.split_arg(line),self,self.history)
  File "/Applications/madanalysis5/madanalysis/interpreter/cmd_import.py", line 83, in do
    self.ImportJob(filename,myinterpreter,history)
  File "/Applications/madanalysis5/madanalysis/interpreter/cmd_import.py", line 148, in ImportJob
    answer=input("Answer: ")
UnboundLocalError: local variable 'input' referenced before assignment
```
[ttbarPlot.zip](https://github.com/MadAnalysis/madanalysis5/files/9853313/ttbarPlot.zip)

**Comment by jackaraz** [comment]
Hi @robinhayes, thanks for the report; I can indeed reproduce your issue in v1.10, where the `import` command does not register, and I get the same error as you do. I'll note this down and fix it for the next release. For the root portion of your issue, the manual you are using is extremely old (2012); hence some of the commands may have been deprecated. I suggest using the 2018 manual, or if you are looking into specific functionalities, we have multiple recent submodule documentations presented in the [README](https://github.com/MadAnalysis/madanalysis5#credits) file. MadAnalysis does not produce any root output anymore unless used with the Delphes package.

**Comment by robinhayes** [comment]
@jackaraz thank you for looking at this! I had no idea there was a more recent manual - I followed the README to the MadAnalysis website and clicked on the "Download the user manual" link, which seemed reasonable at the time. I'll look at the more recent one and appreciate knowing that I'll need to use Delphes if I want a root file. Thanks again!
