### ISSUE TITLE
Install fastjet 

### ISSUE THREAD

**Issue by ArturU043** [MadAnalysis/madanalysis5#151]
### System Settings

macOS 12.0.1
Python 3.9 and Apple clang version 13.1.6 (clang-1316.0.21.2.5)
ma5 verison 1.10.4

### Describe the bug

When installing fastjet an error happens before ending the package download (allways arround 80%)
It prompts a OSError: [Errno 50] Network is down and exits the ma5 interface. 

Happend 4 times in a row. 
Local machine's Network is working just fine. 

ma5>install fastjet
MA5: 
MA5:    **********************************************************
MA5:                       Installing fastjet                    
MA5:    **********************************************************
MA5:    Detecting a previous installation ...
MA5:    => found
MA5:    Removing the previous installation ...
MA5-WARNING: Are you sure to remove the directory called '/Users/acordeir/Documents/LPNHE/ATLAS/MA5/madanalysis5/tools/fastjet' ? (Y/N)
Answer: Y
MA5:    How many cores would you like to use for the compilation ? default = max = 4
   => Answer: 
MA5:    => Number of cores used for the compilation = 4
MA5:    **********************************************************
MA5:    Creating a devoted folder ...
MA5:    Creating a temporary folder ...
MA5:    Downloading the package ...
MA5:     - 1/1 http://madanalysis.irmp.ucl.ac.be/raw-attachment/wiki/WikiStart/fastjet-3.3.3.tar.gz ...
MA5:    'fastjet.tar.gz' is corrupted or is an old version.
         --> Downloading a new package ...
Traceback (most recent call last): 2.79M (84.8%)         
  File "/Users/acordeir/Documents/LPNHE/ATLAS/MA5/madanalysis5/./bin/ma5", line 76, in <module>
    madanalysis.core.launcher.LaunchMA5(version, date, ma5dir)
  File "/Users/acordeir/Documents/LPNHE/ATLAS/MA5/madanalysis5/madanalysis/core/launcher.py", line 430, in LaunchMA5
    repeat = MainSession(mode,arglist,ma5dir,version,date)
  File "/Users/acordeir/Documents/LPNHE/ATLAS/MA5/madanalysis5/madanalysis/core/launcher.py", line 334, in MainSession
    interpreter.cmdloop()
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/cmd.py", line 217, in onecmd
    return func(arg)
  File "/Users/acordeir/Documents/LPNHE/ATLAS/MA5/madanalysis5/madanalysis/interpreter/interpreter.py", line 265, in do_install
    result = self.cmd_install.do(self.split_arg(line))
  File "/Users/acordeir/Documents/LPNHE/ATLAS/MA5/madanalysis5/madanalysis/interpreter/cmd_install.py", line 124, in do
    if installer.Execute('fastjet')==False:
  File "/Users/acordeir/Documents/LPNHE/ATLAS/MA5/madanalysis5/madanalysis/install/install_manager.py", line 140, in Execute
    if not installer.Download():
  File "/Users/acordeir/Documents/LPNHE/ATLAS/MA5/madanalysis5/madanalysis/install/install_fastjet.py", line 91, in Download
    if not InstallService.wget(self.files,logname,self.downloaddir):
  File "/Users/acordeir/Documents/LPNHE/ATLAS/MA5/madanalysis5/madanalysis/install/install_service.py", line 301, in wget
    chunk = info.read(chunk_size)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 463, in read
    n = self.readinto(b)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 507, in readinto
    n = self.fp.readinto(b)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
OSError: [Errno 50] Network is down

### To Reproduce

install fastjet

**Comment by jackaraz** [comment]
Hi @ArturU043, unfortunately, I can not reproduce your error, and it is the first time I have seen something like this. Please check the internet usage permissions in your machine and internet connection. The error is not within madanalysis but from your operating system, i.e. `OSError: [Errno 50] Network is down`.

**Comment by jackaraz** [comment]
Closing this issue then, please feel free to reopen.
