### ISSUE TITLE
My ma5 in v2.0.4-beta version can not  successfully produce expert mode files in reconstructed level. 

### ISSUE THREAD

**Issue by fortuneteller-y** [MadAnalysis/madanalysis5#164]
### Question

I am interested in using ma5 to carried out jet substructure analysis, so I march to ma5 in v2.0.4-beta version. But I didn't successfully generate expert mode files in reconstructed level. The error report in the screen is shown as below.  Additionally, I found that the generated main.cc file is not completed. I know v2 version is a beta version. If you could do me a favor, I would be grateful.  I use ubuntu20 with python3.8. The delphes and the fastjet are installed by ma5 install options.

MA5:    Writing a 'Makefile'...
Traceback (most recent call last):
  File "./bin/ma5", line 75, in <module>
    madanalysis.core.launcher.LaunchMA5(version, date, ma5dir)
  File "/home/ys/work/MA5-2/madanalysis5-2.0.4_beta/madanalysis/core/launcher.py", line 430, in LaunchMA5
    repeat = MainSession(mode,arglist,ma5dir,version,date)
  File "/home/ys/work/MA5-2/madanalysis5-2.0.4_beta/madanalysis/core/launcher.py", line 306, in MainSession
    if not expert.Copy(dirname,config=config_file):
  File "/home/ys/work/MA5-2/madanalysis5-2.0.4_beta/madanalysis/core/expert_mode.py", line 152, in Copy
    if not jobber.CreateBldDir(analysisName=title,outputName="user.saf"):
  File "/home/ys/work/MA5-2/madanalysis5-2.0.4_beta/madanalysis/IOinterface/job_writer.py", line 625, in CreateBldDir
    self.CreateMainFct(file,analysisName,outputName)
  File "/home/ys/work/MA5-2/madanalysis5-2.0.4_beta/madanalysis/IOinterface/job_writer.py", line 560, in CreateMainFct
    for item in self.main.multiparticles.Get("invisible"):
  File "/home/ys/work/MA5-2/madanalysis5-2.0.4_beta/madanalysis/multiparticle/multiparticle_collection.py", line 84, in Get
    return self.table[name]
KeyError: 'invisible

**Comment by jackaraz** [comment]
Hi @ fortuneteller-y, please tell me the commands you run so that I can try to reproduce your issue on my end.

**Comment by fortuneteller-y** [comment]
The command "ma5 -e " is ok. But the command "ma5 -Re" run across the problem as reported.

**Comment by jackaraz** [comment]
Hi @fortuneteller-y, I'll look into it, but for the time being, if you are not providing an SFS card, running expert mode in reco mode does not make sense since you are not providing any information regarding the reconstruction. So it should not work, but it should not crush as well, so that needs fixing. Thanks for letting me know.
