### ISSUE TITLE
Challenges Encountered: Plotting Issues with MadAnalysis

### ISSUE THREAD

**Issue by subhojitphy** [MadAnalysis/madanalysis5#242]
### System Settings

Using Madanalysis5(V1.8). Ubuntu 18.04 system. python2.7.

### Describe the bug

Is it true that in MadAnalysis, only up to 50 LHE files can be imported? I have encountered no issues when importing 50 LHE files or less than that. However, I receive the following error when importing more than 50 LHE files. Can I change anything to allow importing a much larger number of LHE files?

MA5:    Preparing data for the reports ...
MA5:    Generating all plots ...
Traceback (most recent call last):
  File "./ma5", line 70, in <module>
    madanalysis.core.launcher.LaunchMA5(version, date, ma5dir)
  File "/home/subhojit/Tools/MadAnalysis5_v1.8/madanalysis5/madanalysis/core/launcher.py", line 428, in LaunchMA5
    repeat = MainSession(mode,arglist,ma5dir,version,date)
  File "/home/subhojit/Tools/MadAnalysis5_v1.8/madanalysis5/madanalysis/core/launcher.py", line 320, in MainSession
    interpreter.load()
  File "/home/subhojit/Tools/MadAnalysis5_v1.8/madanalysis5/madanalysis/interpreter/interpreter_base.py", line 72, in load
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/home/subhojit/Tools/MadAnalysis5_v1.8/madanalysis5/madanalysis/interpreter/interpreter.py", line 293, in do_submit
    [self.cmd_submit.do](http://self.cmd_submit.do/)(self.split_arg(line),self.history)
  File "/home/subhojit/Tools/MadAnalysis5_v1.8/madanalysis5/madanalysis/interpreter/cmd_submit.py", line 63, in do
    return self.do_submit(args,history)
  File "/home/subhojit/Tools/MadAnalysis5_v1.8/madanalysis5/madanalysis/interpreter/cmd_submit.py", line 216, in do_submit
    self.CreateReports(args,history,layout)
  File "/home/subhojit/Tools/MadAnalysis5_v1.8/madanalysis5/madanalysis/interpreter/cmd_submit.py", line 272, in CreateReports
    if not layout.DoPlots(histopath,modes,output_paths):
  File "/home/subhojit/Tools/MadAnalysis5_v1.8/madanalysis5/madanalysis/layout/layout.py", line 175, in DoPlots
    self.plotflow.DrawAll(histo_path,modes,output_paths,ListPlots)
  File "/home/subhojit/Tools/MadAnalysis5_v1.8/madanalysis5/madanalysis/layout/plotflow.py", line 173, in DrawAll
    irelhisto,filenamePy,output_files)
  File "/home/subhojit/Tools/MadAnalysis5_v1.8/madanalysis5/madanalysis/layout/plotflow.py", line 781, in DrawMATPLOTLIB
    mylinecolor  = '"'+madanalysis.enumeration.color_hex.color_hex[linecolor]+'"'
KeyError: 101
importing

### To Reproduce

Just import more than 50 LHE files in the normal mode MadAnalysis, and they try to plot some variables.

**Comment by jackaraz** [comment]
Hi @subhojitphy, you are using a veeeeery old version of madanalysis; we don't even support Python 2 anymore. Can you please try it with the latest version?

**Comment by subhojitphy** [comment]
@jackaraz  I have just tried the latest version of madanalysis(v1.10.12), which is installed with python3. I am using Python 3.8.0. I still get the same error when importing more than 50 LHE files. It would be helpful if you could let me know the solution for this at your earliest convenience.

**Comment by subhojitphy** [comment]
@jackaraz Able to solve it by setting linecolor and linestyle for each of the files. Thanks...
